api_v1:
    resource:
        path: ../src/Controller/Api/V1/
        namespace: App\Controller\Api\V1
    type: attribute
    prefix: /api/v1
    name_prefix: api_v1_
    format: json
    stateless: true
    utf8: true
    requirements:
        partnerId: '[^/]{1,64}'
        orderId: '[^/]{1,64}'
