services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Order/Application/Dto/'
            - '../src/Order/Domain/'
            - '../src/Order/Infrastructure/Http/Request/'
            - '../src/Order/Infrastructure/Http/Response/'
            - '../src/Order/Infrastructure/Http/Validator/'
            - '../src/Shared/Problem/'

    App\Order\Domain\Repository\OrderRepositoryInterface: '@App\Order\Infrastructure\Doctrine\DoctrineOrderRepository'
